### ISSUE TITLE
Issues with anno command

### ISSUE THREAD

**Issue by avannan** [yangence/DEBKS#7]
Hi,

I've been following the tutorial but using my own data, and I'm running into an error with the anno command.

My code:
DEBKS anno -c merge_pos.txt -m Rn6_genome.fa -g Rn6_annotation_sorted.gtf.gz -o ciri2_debks_anno

Error:
Traceback (most recent call last):
  File "/home/avannan/miniconda3/envs/circ_analysis/bin/DEBKS", line 11, in <module>
    sys.exit(main())
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/debks/DEBKS_main.py", line 38, in main
    anno.anno(docopt(anno.__doc__, version=__version__))
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/debks/anno.py", line 70, in anno
    annoPos=pd.DataFrame(circPos.apply(lambda x: pos2ano(x,gtfFile,faFile),axis=1).tolist(),columns=['type','strand','gene_id','gene_name','subtype','exon_start','exon_end','len'])
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/pandas/core/frame.py", line 8736, in apply
    return op.apply()
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/pandas/core/apply.py", line 688, in apply
    return self.apply_standard()
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/pandas/core/apply.py", line 812, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/pandas/core/apply.py", line 828, in apply_series_generator
    results[i] = self.f(v)
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/debks/anno.py", line 70, in <lambda>
    annoPos=pd.DataFrame(circPos.apply(lambda x: pos2ano(x,gtfFile,faFile),axis=1).tolist(),columns=['type','strand','gene_id','gene_name','subtype','exon_start','exon_end','len'])
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/debks/anno.py", line 318, in pos2ano
    return(list(adjGene(chr,start,end+1,gtfFile,strand)))
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/debks/anno.py", line 255, in adjGene
    anno=getGene(chr,start,end,gtfFile)
  File "/home/avannan/miniconda3/envs/circ_analysis/lib/python3.7/site-packages/debks/anno.py", line 106, in getGene
    geneDict[gtf.transcript_id].append([gtf.start,gtf.end,gtf.gene_id,gtf.gene_name,gtf.strand])
  File "pysam/libctabixproxies.pyx", line 635, in pysam.libctabixproxies.GTFProxy.__getattr__
KeyError: 'gene_name'

I saw that there were previous errors with the anno command and that it was updated, so I do have the latest version.

Thanks!

**Comment by colinliuzelin** [comment]
Hi,
It seems like your gtf file does not contain the **gene_name**. For example: 
chr1	HAVANA	gene	11869	14412	.	+	.	gene_id "ENSG00000223972.4"; transcript_id "ENSG00000223972.4"; gene_type "pseudogene"; gene_status "KNOWN"; **gene_name** "DDX11L1"; transcript_type "pseudogene"; transcript_status "KNOWN"; transcript_name "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2";
Could you show me your gtf file? or give me a download link. I could further confirm the problem and make a fix.
Alternatively, you can add the **gene_name** in your gtf file and try it again.
